// Mocks generated by Mockito 5.4.6 from annotations
// in kanban_board/test/features/task_management/views/cubit/comment_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kanban_board/features/task_management/data/repository/comment_repository.dart'
    as _i2;
import 'package:kanban_board/features/task_management/domain/entities/comment.dart'
    as _i3;
import 'package:kanban_board/features/task_management/domain/usecases/add_comment.dart'
    as _i4;
import 'package:kanban_board/features/task_management/domain/usecases/fetch_comments.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCommentRepository_0 extends _i1.SmartFake
    implements _i2.CommentRepository {
  _FakeCommentRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComment_1 extends _i1.SmartFake implements _i3.Comment {
  _FakeComment_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AddComment].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddComment extends _i1.Mock implements _i4.AddComment {
  MockAddComment() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommentRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCommentRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CommentRepository);

  @override
  _i5.Future<_i3.Comment> call(_i3.Comment? comment) =>
      (super.noSuchMethod(
            Invocation.method(#call, [comment]),
            returnValue: _i5.Future<_i3.Comment>.value(
              _FakeComment_1(this, Invocation.method(#call, [comment])),
            ),
          )
          as _i5.Future<_i3.Comment>);
}

/// A class which mocks [FetchComments].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchComments extends _i1.Mock implements _i6.FetchComments {
  MockFetchComments() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommentRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCommentRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CommentRepository);

  @override
  _i5.Future<List<_i3.Comment>> call(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [taskId]),
            returnValue: _i5.Future<List<_i3.Comment>>.value(<_i3.Comment>[]),
          )
          as _i5.Future<List<_i3.Comment>>);
}
