// Mocks generated by Mockito 5.4.6 from annotations
// in kanban_board/test/features/task_management/views/cubit/task_managment_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kanban_board/features/kanban_board/domain/entities/task.dart'
    as _i2;
import 'package:kanban_board/features/task_management/domain/usecases/create_task.dart'
    as _i3;
import 'package:kanban_board/features/task_management/domain/usecases/update_task.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CreateTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateTask extends _i1.Mock implements _i3.CreateTask {
  MockCreateTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Task> call(_i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#call, [task]),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#call, [task])),
            ),
          )
          as _i4.Future<_i2.Task>);
}

/// A class which mocks [UpdateTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateTask extends _i1.Mock implements _i5.UpdateTask {
  MockUpdateTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Task> call(_i2.Task? task, String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [task, id]),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#call, [task, id])),
            ),
          )
          as _i4.Future<_i2.Task>);
}
