// Mocks generated by Mockito 5.4.6 from annotations
// in kanban_board/test/features/task_management/data/reposiitory/task_management_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kanban_board/core/sync/data/data_source/sync_queue_data_source.dart'
    as _i6;
import 'package:kanban_board/core/sync/data/models/sync_queue_item.dart' as _i7;
import 'package:kanban_board/features/kanban_board/data/data_source/task_local_data_source.dart'
    as _i2;
import 'package:kanban_board/features/kanban_board/data/models/task_local_model.dart'
    as _i5;
import 'package:kanban_board/features/kanban_board/domain/entities/task.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TaskLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskLocalDataSource extends _i1.Mock
    implements _i2.TaskLocalDataSource {
  MockTaskLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Task>> getTasks(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, [projectId]),
            returnValue: _i3.Future<List<_i4.Task>>.value(<_i4.Task>[]),
          )
          as _i3.Future<List<_i4.Task>>);

  @override
  _i3.Future<void> upsertTask(_i5.TaskLocalModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#upsertTask, [task]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveTasks(List<_i5.TaskLocalModel>? tasks) =>
      (super.noSuchMethod(
            Invocation.method(#saveTasks, [tasks]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.TaskLocalModel>> getUnsyncedTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedTasks, []),
            returnValue: _i3.Future<List<_i5.TaskLocalModel>>.value(
              <_i5.TaskLocalModel>[],
            ),
          )
          as _i3.Future<List<_i5.TaskLocalModel>>);
}

/// A class which mocks [SyncQueueDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncQueueDataSource extends _i1.Mock
    implements _i6.SyncQueueDataSource {
  MockSyncQueueDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> enqueue(_i7.SyncQueueItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.SyncQueueItem>> getReadyItems(DateTime? now) =>
      (super.noSuchMethod(
            Invocation.method(#getReadyItems, [now]),
            returnValue: _i3.Future<List<_i7.SyncQueueItem>>.value(
              <_i7.SyncQueueItem>[],
            ),
          )
          as _i3.Future<List<_i7.SyncQueueItem>>);

  @override
  _i3.Future<void> update(_i7.SyncQueueItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> remove(_i7.SyncQueueItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
