// Mocks generated by Mockito 5.4.6 from annotations
// in kanban_board/test/features/kanban_board/domain/cubit/task_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kanban_board/features/kanban_board/data/repository/task_repository.dart'
    as _i2;
import 'package:kanban_board/features/kanban_board/domain/entities/task.dart'
    as _i5;
import 'package:kanban_board/features/kanban_board/domain/usecases/fetch_tasks.dart'
    as _i3;
import 'package:kanban_board/features/kanban_board/domain/usecases/initial_sync_tasks.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskRepository_0 extends _i1.SmartFake
    implements _i2.TaskRepository {
  _FakeTaskRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FetchTasks].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchTasks extends _i1.Mock implements _i3.FetchTasks {
  MockFetchTasks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTaskRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TaskRepository);

  @override
  _i4.Future<List<_i5.Task>> call(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [projectId]),
            returnValue: _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
          )
          as _i4.Future<List<_i5.Task>>);
}

/// A class which mocks [InitialSyncTasks].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitialSyncTasks extends _i1.Mock implements _i6.InitialSyncTasks {
  MockInitialSyncTasks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [projectId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
