// Mocks generated by Mockito 5.4.6 from annotations
// in kanban_board/test/core/sync_engine/sync_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kanban_board/core/network/network_info_impl.dart' as _i2;
import 'package:kanban_board/core/sync/data/data_source/sync_queue_data_source.dart'
    as _i4;
import 'package:kanban_board/core/sync/data/models/sync_queue_item.dart' as _i5;
import 'package:kanban_board/features/kanban_board/data/data_source/task_local_data_source.dart'
    as _i7;
import 'package:kanban_board/features/kanban_board/data/models/task_local_model.dart'
    as _i9;
import 'package:kanban_board/features/kanban_board/domain/entities/task.dart'
    as _i8;
import 'package:kanban_board/features/task_management/data/data_source/task_management_data_source.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NetworkInfoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfoImpl extends _i1.Mock implements _i2.NetworkInfoImpl {
  MockNetworkInfoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Stream<bool> get onStatusChange =>
      (super.noSuchMethod(
            Invocation.getter(#onStatusChange),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);
}

/// A class which mocks [SyncQueueDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncQueueDataSource extends _i1.Mock
    implements _i4.SyncQueueDataSource {
  MockSyncQueueDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> enqueue(_i5.SyncQueueItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.SyncQueueItem>> getReadyItems(DateTime? now) =>
      (super.noSuchMethod(
            Invocation.method(#getReadyItems, [now]),
            returnValue: _i3.Future<List<_i5.SyncQueueItem>>.value(
              <_i5.SyncQueueItem>[],
            ),
          )
          as _i3.Future<List<_i5.SyncQueueItem>>);

  @override
  _i3.Future<void> update(_i5.SyncQueueItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> remove(_i5.SyncQueueItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [TaskManagementDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskManagementDataSource extends _i1.Mock
    implements _i6.TaskManagementDataSource {
  MockTaskManagementDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> createTask(
    Map<String, dynamic>? taskContent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [taskContent]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> updateTask(
    Map<String, dynamic>? updatedTaskContent,
    String? taskId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [updatedTaskContent, taskId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [TaskLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskLocalDataSource extends _i1.Mock
    implements _i7.TaskLocalDataSource {
  MockTaskLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i8.Task>> getTasks(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, [projectId]),
            returnValue: _i3.Future<List<_i8.Task>>.value(<_i8.Task>[]),
          )
          as _i3.Future<List<_i8.Task>>);

  @override
  _i3.Future<void> upsertTask(_i9.TaskLocalModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#upsertTask, [task]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveTasks(List<_i9.TaskLocalModel>? tasks) =>
      (super.noSuchMethod(
            Invocation.method(#saveTasks, [tasks]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.TaskLocalModel>> getUnsyncedTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedTasks, []),
            returnValue: _i3.Future<List<_i9.TaskLocalModel>>.value(
              <_i9.TaskLocalModel>[],
            ),
          )
          as _i3.Future<List<_i9.TaskLocalModel>>);
}
