name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Android App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      # Set up environment variables
      - name: Set environment variables
        run: |
          echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          # Add other secrets as needed

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run build_runner
      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Run tests
      - name: Run tests
        run: flutter test

      # Build APK
      - name: Build APK
        run: flutter build apk --release
